### PR TITLE
fixed spi config defaulting to SPI2

### PR DESCRIPTION
**Pull request by nickycakes**

### CODE REVIEW

**Comment by nickycakes** [comment]
phase bit default also doesn't appear to be the same as hydrabus defaults

**Comment by bvernoux** [comment]
Default SPI2 speed shall be also changed in following parts
- https://github.com/hydrabus/pyHydrabus/blob/ec4276229036d7fe841b3edf4bcc5aea852db212/pyHydrabus/spi.py#L27
- https://github.com/hydrabus/pyHydrabus/blob/ec4276229036d7fe841b3edf4bcc5aea852db212/pyHydrabus/spi.py#L57

**Comment by bvernoux** [comment]
@nickycakes Could you provide an update on that PR ?

**Comment by Baldanos** [comment]
Sorry for the long wait, this PR went under my radar.

All good to me. Thanks for the contribution !

**Pull request merged**
